module.exports = {
    themes: [
        "terrain",
        "landforms",
        "landscapes",
        "topography",
        "the Geologic time scale",
        "rock types",
        "the Litosphere",
        "plate tectonics",
        "volcanoes",
        "earthquakes",
        "tsunamis",
        "mountains",
        "exogenous terrain processes",
        "the Earth's weather",
        "precipitation",
        "the Climate",
        "the geographic distribution on climatic elements",
        "climate modifiers",
        "the planetary wind circulation",
        "air pressure",
        "the World Ocean",
        "seawater properties",
        "sea currents",
        "tides",
        "seas",
        "shores",
        "islands",
        "oceans",
        "rivers",
        "lakes",
        "swamps",
        "tropical rain forests",
        "taiga and tundra",
        "high mountain areas",
        "soil types",
        "soil degradation",
        "desertification",
        "desert and semi-desert areas",
        "deforestation",
        "forests",
        "plant cover on Earth",
        "populations",
        "population distribution and movement",
        "the demographic structure of populations",
        "globalization",
        "the impact of globalization",
        "international integrations and organizations",
        "labor migrations",
        "settlements",
        "the morphological structure of settlements",
        "the differentiation of urban and rural settlements",
        "urban settlements",
        "urbanization",
        "cities",
        "socioeconomic polarisation in cities",
        "the evnironmental, economic and demographic sustainability of cities",
        "spatial planning",
        "the economy",
        "the structure of the economy",
        "socioeconomic development indicators",
        "energy production and consumption",
        "the spatial distribution of energy sources",
        "energy and mining",
        "natural resources in various countries",
        "the importance of industry for economic development",
        "economic development indicators",
        "sustainable development",
        "waste management",
        "glacial and interglacial periods",
        "the greenhouse effect",
        "human influence on greenhouse gas emissions",
        "anthropogenic factors of climate change",
        "natural factors of climate change",
        "El Niño",
        "the consequences of climate change",
        "the economic explotation of the sea",
        "the protection of the sea and the underwater world",
        "the seabed",
        "countries",
        "country borders",
        "political maps",
        "national flags",
        "elements of national identity",
        "multiculturalism",
        "the influence of globalization processes on the sovereignty of states",
        "the impact of globalization processes on the perservation of national identities",
        "cultural regions",
        "the world superpowers",
        "the basic forms of agricultural production",
        "the impact of market trends on food production",
        "the world agricultural production",
        "food availability and the problem of hunger in the world",
        "the advantages and disadvantages of modern trends in food production",
        "the connection between transport and trade",
        "the world trade and financial flows",
        "the emergence and development of tourism",
        "tourism development and its consequences",
        "sustainable tourism"
    ]
}