module.exports = {
    themes: [
        "the Neolithic Revolution",
        "ancient civilizations",
        "Ancient Egypt",
        "Ancient Greece",
        "Athens in Ancient Greece",
        "art and science in Ancient Greece",
        "the olympic games in Ancient Greece",
        "Greek mythology",
        "the Peleponnesian War",
        "Alexander the Great",
        "Ancient Rome",
        "the Roman Republic",
        "civil wars in the Roman Republic",
        "Gaius Julius Caesar",
        "the Roman Empire",
        "'Five Good Emperors' in the Roman Empire",
        "emperor Diocletian",
        "emperor Constantine the Great",
        "the fall of the Roman Empire",
        "the Byzantine Empire",
        "emperor Justinian",
        "the Islamic conquest of Spain",
        "the Frankish state",
        "the Holy Roman Empire",
        "the year 1066 in England",
        "the East-West religious schism",
        "Feudalism",
        "the Magna Carta",
        "the Mongol invasions and conquests",
        "the Black Death plague pandemic",
        "the Hundred Years' War",
        "the Reinassance",
        "the rise of the Ottoman Empire",
        "the fall of Constantinople",
        "the Age of Discovery",
        "Portuguese maritime exploration",
        "European maritime exploration",
        "the Aztec Empire",
        "the Inca Empire",
        "the Maya Empire",
        "the Scientific Revolution",
        "the Protestant Reformation",
        "the Thirty Years' War",
        "the Age of Absolutism",
        "french king Louis XIV",
        "the English Revolution",
        "the Seven Years' War",
        "the Thirteen Colonies",
        "the European colonization",
        "the Age of Englightment",
        "Liberalism",
        "the Industrial Revolution",
        "the American Revolution",
        "the French Revolution",
        "french revolutionary wars",
        "the Napoleonic Wars",
        "the Latin American independence",
        "the Burbon Restoration in France",
        "the revolutions of 1848",
        "Socialism",
        "the Crimean War",
        "the American Civil War",
        "american expansion to the West",
        "Opium Wars",
        "the Meiji Restoration",
        "the Italian unification",
        "the German unification",
        "the Franco-Prussian War",
        "the Paris Commune",
        "the Age of Imperialism",
        "the Scramble for Africa",
        "the British colonial Empire",
        "british colonial rule of India",
        "the French colonial Empire",
        "the Second Industrial Revolution",
        "the First Sino-Japanese War",
        "the Russo-Japanese War",
        "the last years of the Chinese Empire",
        "the decline of the Ottoman Empire",
        "the Russo-Turkish War",
        "the Berlin Congress",
        "the French Revanchism",
        "the Italian Irredentism",
        "the First Balkan War",
        "the Second Balkan War",
        "the assasination of Franz Ferdinand",
        "the western front in the First World War",
        "the eastern front in the First World War",
        "the February Revolution",
        "the October Revolution",
        "the end of the First World War",
        "the aftermath of the First World War",
        "the League of Nations",
        "the Russian Civil War",
        "the New Economic Policy in the Soviet Union",
        "the Turkish War of Independence",
        "the rise of Faschism in Italy",
        "Faschism",
        "the Weimar Republic",
        "the Great Depression",
        "national-socialism in Germany",
        "Stalin's rule in Soviet Union",
        "the New Deal in the United States",
        "the United Kingdon in the Interwar period",
        "France in the interwar period",
        "the Spanish Civil War",
        "japanese militarism in the Interwar period",
        "the Second Sino-Japanese War",
        "the Chinese Civil War",
        "the Second World War",
        "the Pacific War in the Second World War",
        "the Manhattan Project",
        "the atomic bombing of Japan",
        "the United Nations",
        "the reconstruction of Europe after the Second World War",
        "the Cold War",
        "the Informbiro Resolution",
        "the Korean War",
        "the partition of India",
        "the 1953 Iranian coup d'etat",
        "the 1954 Guatemalan coup d'etat",
        "the Algerian War",
        "the Suez Crisis",
        "the Hungarian Revolution",
        "the Cuban Revolution",
        "Decolonization",
        "the Third World",
        "the Non-aligned movement in the Cold War",
        "the Space Race",
        "the Vietnam War",
        "the Civil rights movement in the United States",
        "the Cultural Revolution",
        "the Arab-Israeli Wars",
        "the Prague Spring",
        "the 1973 Chilean coup d'etat",
        "the 1973 OPEC oil embargo",
        "the Carnation Revolution",
        "the Islamic Revolution in Iran",
        "the Afghan-Soviet War",
        "the Iran-Iraq War",
        "the Solidarity movement",
        "the global economic system after the Second World War",
        "Neocolonialism",
        "the fall of communism in Eastern Europe",
        "the breakup of Yugoslavia",
        "the dissolution of the Soviet Union",
        "the process of european unification"
    ]
}